name: 'Logger'
description: 'log jobs into repository'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm cache
      shell: bash
      env:
        l_repo_url: "https://github.com/krapjost/knit"
        l_file_name: ""
        l_action_run_url: ""
        l_commit_url: ""
        l_commit_hash: ""

      run: |
        l_file_name="logs/$(date +%y%m%d).ci.${{ github.job }}.gen.md"
        l_commit_hash=$(git log -1 --pretty=%h)
        l_commit_url="$l_repo_url/commit/$l_commit_hash"
        l_action_run_url="$l_repo_url/actions/runs/${{ github.run_id }}"

        touch $l_file_name
        echo "### 🔨 run [ci.build]($l_action_run_url) for [$l_commit_hash]($l_commit_url)" >> $l_file_name
        echo '```yaml' >> $l_file_name
        echo $(git log -1 --pretty=%s) >> $l_file_name
        echo "by: $(git log -1 --pretty=%ce)" >> $l_file_name
        echo '```' >> $l_file_name
        echo >> $l_file_name

        git config user.name github-actions
        git config user.email github-actions@github.com
        git add . && git commit -m "log: write ci build log"
        git push
