name: Production branch protection

on:
  pull_request:
    - "prod"

jobs:
  protect_production_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Allow merge to Prod only from Staging or Hotfix
        if: github.base_ref == 'prod'
          && github.head_ref != 'staging'
          || github.head_ref != 'hotfix-*'
        run: |
          echo "ERROR: You can only merge to prod from staging"
          exit 1
