name: CI
 
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build:
    name: Build and Test
    permissions:
      contents: write
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 🖊️ Log
        env:
          log_file: "logs/$(eval 'date +%y%m%d').${{ github.job }}.gen.md"
        run: |
          touch $log_file
          echo "## 🔨 ci.build started - $(date +%R)\n" >> $log_file
          echo "> ### $(git log -1 --pretty=format:%s)\n" >> $log_file
          echo "> - $(git log -1 --pretty=format:%ce)\n\n" >> $log_file

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "log: write ci build log"
          git push

      - name: 🔧 Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: 📥 Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
