name: CI
 
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          touch logs/$(date +%y_%m_%d).build.md
          echo "$(date +%R): CI.build started by $(git log -1 --pretty=format:%cm)" >> logs/$(date +%y_%m_%d).build.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "log: write ci build log"
          git push

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: 📥 Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
