name: CI
 
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🔧 Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: 📥 Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: 🚧 Build
        run: pnpm build

      - name: 🧪 Test
        run: pnpm test

      - name: 祝Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            dist/web

  deploy-web:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name:  Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: dist/web

      - name: Deploy web
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: 'ps-knot.surge.sh'
          project: 'dist/web'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}

