name: Production

on:
  pull_request:
    branches:
      - production
    types: [opened, synchronize, closed]

jobs:
  call-deployment:
    if: github.event.pull_request.merged
    uses: ./.github/workflows/deployment.yaml
    with:
      discord-message: "PR merged to production"
      deploy-target: "production"

  call-discord:
    if: github.event.pull_request.merged != true
    uses: ./.github/workflows/discord.yaml
    with:
      message: "PR requested to production"
