name: Push

on:
  push:
    branches:
      - discord-github-action

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send a Discord notification on push
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "New Push Detected"
          description: ${{ github.event.description }}
          url: "https://github.com/parkingspace/knot"
          username: GitHubBot
