name: Staging

on:
  push:
    branches:
      - "staging"
    paths:
      - "apps/**"
      - "pkgs/**"
      - ".github/**"
  pull_request:
    branches:
      - "staging"
    types: [synchronize]

jobs:
  build-web:
    name: Build web app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🔧 Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: 📥 Install pnpm
        uses: ./.github/actions/pnpm-install

      - name: 🚧 Build & Test
        run: pnpm web build && pnpm web test

      - name:  Upload web build
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: dist/web

  deploy-web:
    name: Deploy web app
    needs: build-web
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v3

      - name:  Download web build
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: dist/web

      - name: 🌏 Deploy web
        uses: dswistowski/surge-sh-action@v1.0.1
        with:
          domain: "ps-knot-stage.surge.sh"
          project: "dist/web"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
